on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 */1 * *"
name: create release
permissions:
  contents: write
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm install # or pnpm install / yarn install / bun install

      - name: Build and Zip All Types
        run: |
          set -e
          for type in github blog lockpass bytefuse; do
            echo "Building for $type"
            npm run build:$type --prefix blog
            echo "Zipping dist for $type"
            zip -r dist_${type}.zip blog/docs/.vitepress/dist/*
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number}}
          release_name: Release_${{ github.run_number}}
          body: |
            Changes in this Release
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          set -e
          for file in ./dist_*.zip; do
            if [ -f "$file" ]; then
              echo "Uploading $file..."
              gh release upload ${{ github.run_number }} "$file" --repo ${{ github.repository }}
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
